### ISSUE TITLE
Error: "next start" does not work with "output: export" configuration. Use "npx serve@latest out" instead.

### ISSUE THREAD

**Issue by pupadupa** [thakkaryash94/chroma-ui#5]
```
sudo apt install npm
npm install
npm run build
npm run start

```
gives me this error (on ubuntu 24.04):
```

> chroma-ui@1.0.0 start
> next start

   ▲ Next.js 14.0.3
   - Local:        http://localhost:3000

Error: "next start" does not work with "output: export" configuration. Use "npx serve@latest out" instead.
    at /home/pupadupa/dev/chroma-ui/node_modules/next/dist/server/next.js:208:31
    at async NextServer.prepare (/home/pupadupa/dev/chroma-ui/node_modules/next/dist/server/next.js:152:24)
    at async initializeImpl (/home/pupadupa/dev/chroma-ui/node_modules/next/dist/server/lib/render-server.js:91:5)
    at async initialize (/home/pupadupa/dev/chroma-ui/node_modules/next/dist/server/lib/router-server.js:103:22)
    at async Server.<anonymous> (/home/pupadupa/dev/chroma-ui/node_modules/next/dist/server/lib/start-server.js:236:36)

```

**Comment by thakkaryash94** [comment]
Yes, you are correct. Because we are exporting the static build into out folder. We will need to run `npx serve@latest out` command to run the application. I am updating the README.md
